### ISSUE TITLE
Fix the error in the CircleCI pipeline

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#16]
The CircleCI pipeline is currently using a dependency called Auto to automatically update the release number when changes are pushed to master. 

The dependency isn't working and is causing the pipeline to fail. We can either: 

- fix the problem with the Auto dependency so that we hold onto the automatic release functionality (this is the preferred way)
- or we remove the Auto command from the CircleCI config file in root and manually update releases for the time being

**Comment by kcouliba** [comment]
Hey @daniel-norris, may I'd like to see what a can do with that issue. Mind if I try ?

**Comment by daniel-norris** [comment]
Hey @kcou. Sure thing, thanks for offering to help. I've assigned it to you.

**Comment by KartikSoneji** [comment]
Hi @daniel-norris , @kcouliba 

I had a quick look at the circle ci config file, and the issue is that you have to use `npm run <script>` instead of `npm <script>` to run a script.

The fix is quite simple:
```diff
diff --git a/.circleci/config.yml b/.circleci/config.yml
index ac3696b..25ba7ae 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,7 +15,7 @@ jobs:
             - run: |
                 if [ $CIRCLE_BRANCH = "master" ]
                 then
-                  npm release
+                  npm run release
                 fi
 workflows:
   build-and-test:
```

I didn't notice @kcouliba 's comment at that time, so I am OK with them making this pull request.

**Comment by daniel-norris** [comment]
Hey @KartikSoneji, sure go ahead :)

**Comment by kcouliba** [comment]
@KartikSoneji I didn't even notice that. I am struggling to make the package work on a simple side project. Feel free to PR your solution ;)

**Comment by KartikSoneji** [comment]
@daniel-norris 
Something very concerning is that you have the chromatic project token hardcoded and visible in plain text.
That means anyone can publish potentially malicious code as an update to the package.
Also, any forks that push to master will also unintentionally publish an update to the package.

The correct way is to make the token an environment variable as a CircleCI secret, and only publish the package if the token is present.
I will make the changes to the circleci config, but you will have to add the token as a secret in the CircleCI dashboard.
I **strongly** recommend resetting the chromatic project token, since the old one is already public.
